- name: Preparing kubernetes master node
  hosts: master
  vars_files:
  - ./env.yml
  gather_facts: no
  tasks:
  - name: intializing kubernetes cluster
    shell: 
      cmd: | 
        kubeadm init --pod-network-cidr={{ cidr_v }} --apiserver-advertise-address={{ master_addr }}
    become: true

  - name: create kube directory in root's home directory
    shell:
      cmd: |
        mkdir mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config
        export KUBECONFIG=/etc/kubernetes/admin.conf
    become: true

  - name: create pod's network in master node
    shell:
      cmd: |
        kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
        kubectl taint nodes --all node-role.kubernetes.io/master-
    become: true
  
  - name: Joining worker node to cluster # Generating token to join worker nodes
    shell: 
      cmd: |  
        kubeadm token create --print-join-command
    register: join_token
    become: true
  - debug: msg="{{ join_token.stdout }}"
    
  - name: Copy join command to local file
    local_action: copy content="{{ join_token.stdout_lines[0] }}" dest="/tmp/join_token" mode=0777
    become: true

